Install card collection
dpc-sdp/tide_automated_listing pull request #2
Opened 2020-12-01 04:32 UTC by asarfara

Related Ticket: https://digital-engagement.atlassian.net/browse/TVD-198

This feature adds refactoring of couple of fields so they can be used by both automated_cards and individual_cards.

**Added:**
- Added layout settings to be controlled through Drupal Display UI.
- Added content based fields through Drupal Form UI so they are not a part of  automated_card and can be used by individual_cards.
- Added new widget to allow usage conditional rendering of fields.

**Removed:**
- Removed content based fields from the code.
- Removed layout settings from the code.

**Remaining:**
- Custom logic to set default value for fields that has been taken outside of the automated_cards to make sure we can fill them based on what was set previously. This will allow us to deprecate fields rather than introducing a migration.

Note:
JSON still includes all the fields to maintain backward compatibility.

2020-12-03 22:35 UTC, anthony-malkoun commented
> Remaining:
> 
> Custom logic to set default value for fields that has been taken outside of the automated_cards to make sure we can fill them based on what was set previously. This will allow us to deprecate fields rather than introducing a migration.

This is the outstanding issue for me. Otherwise I'm ok with how this has been implemented. It makes sense for our use case to move those fields out from the component into Drupal fields as they are shared by two components now. 

@sonnykt this module doesn't have a tagged/released version but you said that it is being used by Salsa sites? What happens to those sites if they tried to use this branch? Are those sites using this repo or the original one created by Salsa?

If this was a released module then, while deprecating fields is fine, and ideally, we would try to provide a pathway to users of the module for when the deprecated fields are removed and it becomes a breaking change. I would argue that even this change though is a breaking change as it stands as it would require action on the part of any site that was using this module. Who should provide that migration path? We can't lock ourselves down to forever providing backward compatibility and at times we will need to do breaking changes that are a bump of the major version.

@asarfara because of the time constraints of the TV project, I recommend continuing to use this branch as is. There will need to be some work do to bring this back into core SDP (mainly, getting it working for Solar as well as Together) and I would lean towards providing a migration and cleaning the code up.

2020-12-03 22:45 UTC, sonnykt commented
@anthony-malkoun we are not using this repo for our site as it is still in private. We have our own repo and `dpc-sdp/tide_automated_listing` was originally a copy. Modifying the module in this repo should not affect our site until this module is included in SDP distro.

2020-12-03 23:12 UTC, anthony-malkoun commented
This is a bit of a mess as Solar have it but are actually using a branch reference in their `composer.json` which is less than ideal. We'll mark this branch as a beta I think and as mentioned there will be a task to pull this together which will include a migration if required.

2020-12-07 01:16 UTC, sonnykt commented on tide_automated_listing.install
> +          } catch (\Exception $exception) {
`catch` mút be on a new line.

2020-12-07 01:17 UTC, sonnykt commented on src/Plugin/Field/FieldType/AutomatedListingConfiguration.php
> +        'index' => 'node',
CS issue: incorrect indentation.

2020-12-07 01:23 UTC, sonnykt requested changes

2020-12-07 01:23 UTC, sonnykt commented on src/Plugin/Field/FieldWidget/AutomatedListingConfigurationWidgetEnhanced.php
> +  protected function saveFilterValues($field_id, $wrapper) {
CS issue: no PHPDoc.

2020-12-07 01:23 UTC, sonnykt commented on src/Plugin/jsonapi/FieldEnhancer/AutomatedListingConfigurationEnhancer.php
> +  protected function setDefaultKeys() {
CS issue: no PHPDoc.

2020-12-07 01:23 UTC, sonnykt commented on src/Plugin/Field/FieldWidget/AutomatedListingConfigurationWidgetEnhanced.php
> +      /** Deprecated Fields Start */
CS issue: C-style inline comment is discouraged within functions, and `/** */` should be only used to start a PHPDoc block.

2020-12-07 03:13 UTC, asarfara commented
Hey @sonnykt can you give this one last go :) I have fixed indentation issues.

2020-12-07 03:31 UTC, merged